// docs/HEDERA.md is generated from the committed record, between two markers.
// Everything outside the markers is left alone, so T04, T05 and T06 can fill in
// their own sections without the next setup run overwriting them, and a run
// that changes nothing produces a byte-identical file.
import {
  ACCOUNT_ROLES,
  ROLE_FUNDING_HBAR,
  type AccountRole,
  entityIdToEvmAddress,
  envNamesForRole,
  fromMinorUnits,
  hashscanUrl,
} from './derive.js';
import { TOPIC_NAMES, type HederaRecord } from './plan.js';

export const BEGIN_MARKER = '<!-- begin generated by pnpm hedera:setup -->';
export const END_MARKER = '<!-- end generated by pnpm hedera:setup -->';

const ROLE_PURPOSE: Record<AccountRole, string> = {
  oracle: 'publishes ODI observations to the index topic and holds the ORACLE role',
  api: 'binds policies, signs the CLAIMS authorisation, writes the payments topic',
  steward: 'buys cover over x402 and pays the premium schedule',
  adjuster: 'decides claims and writes the claims topic',
  'policyholder-1': 'demo worker who buys cover in the web app',
  'policyholder-2': 'demo worker bought for by the Steward agent',
  'policyholder-3': 'demo worker for the declined claim path',
  'investor-1': 'demo noteholder, KYC listed on the ATS series',
  'investor-2': 'demo noteholder, KYC listed on the ATS series',
};

function table(header: string[], rows: string[][]): string {
  const lines = [`| ${header.join(' | ')} |`, `|${header.map(() => '---').join('|')}|`];
  for (const row of rows) {
    lines.push(`| ${row.join(' | ')} |`);
  }
  return lines.join('\n');
}

function link(kind: 'account' | 'token' | 'topic', id: string): string {
  return `[${id}](${hashscanUrl(kind, id)})`;
}

/** The part of docs/HEDERA.md this script owns. Pure: same record, same bytes. */
export function renderGeneratedBlock(record: HederaRecord): string {
  const sections: string[] = [];

  sections.push(
    [
      `Network: Hedera testnet, chain id 296 (0x128) through the Hashio JSON-RPC relay.`,
      ``,
      `Operator: ${link('account', record.operator.accountId)}, EVM address \`${record.operator.evmAddress}\`.`,
      `Operator balance when this file was last changed: ${record.operatorBalanceHbarAtLastChange} HBAR.`,
      `Last changed: ${record.lastChanged}.`,
    ].join('\n'),
  );

  const accountRows = ACCOUNT_ROLES.filter((role) => record.accounts[role]).map((role) => {
    const entry = record.accounts[role];
    const names = envNamesForRole(role);
    return [
      role,
      link('account', entry?.accountId ?? ''),
      `\`${entry?.evmAddress ?? ''}\``,
      `${ROLE_FUNDING_HBAR[role]}`,
      names.id,
      ROLE_PURPOSE[role],
    ];
  });
  sections.push(
    [
      '## Accounts',
      '',
      'Every account carries an ECDSA key with its EVM address set at creation, so',
      'none of them is long-zero and all of them can pass an ECRECOVER check. Keys',
      'are derived from the operator key with HKDF-SHA256 and the label',
      '`creance/testnet/<role>`, so this list is reproducible from the operator key',
      'alone and no derived key is stored anywhere. Testnet only.',
      '',
      table(
        ['Role', 'Account id', 'EVM address', 'Funded HBAR', 'Env name', 'Purpose'],
        accountRows,
      ),
    ].join('\n'),
  );

  const tokenRows: string[][] = [];
  if (record.settlementToken) {
    const token = record.settlementToken;
    tokenRows.push([
      'settlement',
      `${token.name} (${token.symbol})`,
      link('token', token.tokenId),
      `\`${token.evmAddress}\``,
      `${token.decimals}`,
      token.origin === 'provided' ? 'existing testnet token named by TESTNET_USDC_TOKEN_ID' : 'created by this script',
    ]);
  }
  if (record.policyNft) {
    const nft = record.policyNft;
    tokenRows.push([
      'policy receipt',
      `${nft.name} (${nft.symbol})`,
      link('token', nft.tokenId),
      `\`${nft.evmAddress}\``,
      `${nft.decimals}`,
      `non-fungible, freeze default ${nft.freezeDefault ? 'true' : 'false'}`,
    ]);
  }
  const nonTransferability =
    record.policyNft?.freezeDefault === false
      ? [
          '',
          'The policy receipt is non-transferable by freezing the holder after the',
          'transfer, not by a default freeze on the collection: a default freeze does',
          'not compose with automatic association, see the day 0 findings below. Each',
          'bind is associate, transfer, freeze; a second policy for the same holder',
          'needs an unfreeze first.',
        ]
      : [];
  sections.push(
    [
      '## Tokens',
      '',
      'Token EVM addresses are the long-zero form, which is what a Solidity call to',
      'the HTS system contract at 0x167 takes. All settlement amounts are integers in',
      'minor units: 28.00 TUSD is 28000000.',
      ...nonTransferability,
      '',
      table(['Class', 'Name', 'Token id', 'EVM address', 'Decimals', 'Note'], tokenRows),
    ].join('\n'),
  );

  const topicRows = TOPIC_NAMES.filter((name) => record.topics[name]).map((name) => {
    const topic = record.topics[name];
    return [
      name,
      link('topic', topic?.topicId ?? ''),
      `\`${entityIdToEvmAddress(topic?.topicId ?? '0.0.0')}\``,
      topic?.submitKeyRole ? `${topic.submitKeyRole} key` : 'none, public by design',
      topic?.memo ?? '',
    ];
  });
  sections.push(
    [
      '## Topics',
      '',
      'All four topics carry the operator key as admin key so a memo can be fixed.',
      'The submit key is what makes a topic a settlement record: without one, anyone',
      'on testnet can write to it.',
      '',
      table(['Topic', 'Topic id', 'EVM address', 'Submit key', 'Memo'], topicRows),
    ].join('\n'),
  );

  const decimals = record.settlementToken?.decimals ?? 6;
  const symbol = record.settlementToken?.symbol ?? '';
  const distributionRows = ACCOUNT_ROLES.filter((role) => record.distributions[role]).map((role) => [
    role,
    `${fromMinorUnits(BigInt(record.distributions[role] ?? '0'), decimals)} ${symbol}`,
    record.distributions[role] ?? '0',
  ]);
  sections.push(
    [
      '## Demo balances',
      '',
      'Handed out by the setup script so the auto-association path is exercised',
      'before the demo runs. The receiving accounts carry',
      '`maxAutomaticTokenAssociations = -1`, so the first transfer consumes a slot',
      'and the sender pays for it.',
      '',
      table(['Role', 'Balance', 'Minor units'], distributionRows),
    ].join('\n'),
  );

  const findings = record.findings.freezeDefault;
  if (findings) {
    sections.push(
      [
        '## Day 0 findings',
        '',
        `- Freeze default true ${findings.composesWithAutoAssociation ? 'does' : 'does not'} compose with unlimited auto-association: ${findings.detail}`,
        `- NFT metadata limit measured as ${findings.metadataLimit}: ${findings.metadataDetail}`,
        `- Probe collection ${link('token', findings.probeTokenId)}, probe account ${link('account', findings.probeAccountId)}.`,
      ].join('\n'),
    );
  }

  if (record.blocky402) {
    sections.push(
      [
        '## x402 facilitator',
        '',
        `Blocky402 at ${record.blocky402.facilitator} lists \`hedera:testnet\` with fee payer`,
        `${link('account', record.blocky402.feePayer)}. T08 proves a settlement payload against it.`,
      ].join('\n'),
    );
  }

  return sections.join('\n\n');
}

const TEMPLATE_TAIL = `
## Contracts

Filled in by T04. CoverPool and CollateralVault addresses, their long-zero and
EVM forms, the HashScan verification links and the measured gas limits.

## Scheduled transactions

Filled in by T05. The measured maximum expiry window for a long-term scheduled
transaction on testnet, and the link to the one scheduled settlement transfer
that executed.

## Asset Tokenization Studio

Filled in by T06. The Displacement Bond Note series ids, the ERC-3643 token
address, the identity registry and the KYC grants.
`;

/**
 * Put the generated block into the document, keeping everything outside the
 * markers. Returns the file content to write.
 */
export function mergeDocument(existing: string | null, block: string): string {
  const body = `${BEGIN_MARKER}\n\n${block}\n\n${END_MARKER}`;
  if (existing) {
    const begin = existing.indexOf(BEGIN_MARKER);
    const end = existing.indexOf(END_MARKER);
    if (begin !== -1 && end !== -1 && end > begin) {
      return `${existing.slice(0, begin)}${body}${existing.slice(end + END_MARKER.length)}`;
    }
  }
  return `# Hedera testnet resources

Every id below was created by \`pnpm hedera:setup\` against Hedera testnet. The
script is idempotent: it reads \`docs/hedera.testnet.json\`, verifies each id on
the mirror node and creates only what is missing, so running it again prints
"nothing to do" and leaves this file untouched.

The block between the two markers is generated. Add new sections outside it.

${body}
${TEMPLATE_TAIL}`;
}
